### ISSUE TITLE
Adding IMG (or Image in toolbar) does not permit base64 images pasted from clipboard

### ISSUE THREAD

**Issue by jadkisson** [Artem-Schander/quill-paste-smart#18]
The paste event suppresses base64 image conversion when pasting an image from the clipboard even if IMG or the Image option are selected. Looking at the source, it doesn't appear to look at the clipboardData.items collection values of type image. Alternatively, if img/image is permitted, permit the default quill paste behavior for that type.

**Comment by artem-schander** [comment]
Hi @jadkisson,
thank you for raising this issue.
To be clear, you don't mean the image being part of a copied string (as a html tag), but just the image by itself?
If so, you're right. I didn't thought about this. A PR would be highly appreciated. Otherwise I'll implement it by myself as soon as I find some time.
