### ISSUE TITLE
Adding "allowed" tags/attributes not working

### ISSUE THREAD

**Issue by MarcoMoreno** [Artem-Schander/quill-paste-smart#25]
When I paste from the clipboard, I cannot prevent certain attributes not to be stripped.  If I add "class" or "id" to the list of allowed attributes, they still get removed.  If I remove "href" then gets stripped too so it appears to be partially working.

Here's my config:
```
var quill = new Quill('#editor-quill', {
  theme: 'snow',
  modules: {
    clipboard: {
      allowed: {
        tags: [ 'a', 'b', 'strong', 'i', 'em', 'div', 'p', 'ul', 'ol', 'li', 'span', 'br' ],
        attributes: ['class', 'id', 'href', 'rel', 'target'],
      },
    },
  },
});
``` 
Any ideas what I might be doing wrong?  Or is this a bug?

**Comment by artem-schander** [comment]
@MarcoMoreno 
sorry, i somehow missed this one.. i'll take a look

**Comment by artem-schander** [comment]
So I checked this and it seems that this is expected behavior. You can try it yourself and paste something with a class or an id inside the editor on [quills official docs](https://quilljs.com/docs/formats/)

On my end the whitelisted attributes are still there.

If you really need the classes, etc. you can find a lot of different approaches to create custom "styled" formats.
Here is a StackOverflow question regarding this topic I asked a few years ago:
https://stackoverflow.com/questions/64633430/quill-js-keeps-stripping-classes-from-anchor-tags
